// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9z-yedcpF28jg8tiL4JXX47DAyVrZpHo',
    appId: '1:172511463620:web:366ea1f10cd5a093e02191',
    messagingSenderId: '172511463620',
    projectId: 'cut-lost-found-2025',
    authDomain: 'cut-lost-found-2025.firebaseapp.com',
    storageBucket: 'cut-lost-found-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUnVIM_oguZoVSyEGeNTQITrE-R4GruOA',
    appId: '1:172511463620:android:6dc14a5a50657594e02191',
    messagingSenderId: '172511463620',
    projectId: 'cut-lost-found-2025',
    storageBucket: 'cut-lost-found-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBucFInpOf1B7cqcS7XrMXcINin_3eno9I',
    appId: '1:172511463620:ios:ef9970afd61cba1ae02191',
    messagingSenderId: '172511463620',
    projectId: 'cut-lost-found-2025',
    storageBucket: 'cut-lost-found-2025.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFoundMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBucFInpOf1B7cqcS7XrMXcINin_3eno9I',
    appId: '1:172511463620:ios:ef9970afd61cba1ae02191',
    messagingSenderId: '172511463620',
    projectId: 'cut-lost-found-2025',
    storageBucket: 'cut-lost-found-2025.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFoundMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9z-yedcpF28jg8tiL4JXX47DAyVrZpHo',
    appId: '1:172511463620:web:346ccbab57cb706ee02191',
    messagingSenderId: '172511463620',
    projectId: 'cut-lost-found-2025',
    authDomain: 'cut-lost-found-2025.firebaseapp.com',
    storageBucket: 'cut-lost-found-2025.firebasestorage.app',
  );
}
