import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'firebase_options.dart';  // Generated by FlutterFire CLI
import 'app.dart';

/// App entry point.
///
/// Steps:
/// 1. WidgetsFlutterBinding ensures Flutter is ready before async work.
/// 2. Set preferred orientation to portrait only.
/// 3. Firebase.initializeApp() connects to your Firebase project.
/// 4. ProviderScope wraps the entire app so Riverpod providers work everywhere.
/// 5. runApp launches the widget tree.
void main() async {
  // Must be called before any async work in main()
  WidgetsFlutterBinding.ensureInitialized();

  // Lock to portrait mode — phones only
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Transparent status bar so our AppBar colour bleeds to the top
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light,
    ),
  );

  // Initialize Firebase using options generated by `flutterfire configure`
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // ProviderScope is Riverpod's equivalent of a context provider at the root.
  // Every provider in the app is accessible inside this scope.
  runApp(
    const ProviderScope(
      child: CutLostFoundApp(),
    ),
  );
}